### ISSUE TITLE
doesn't seems to get deleted posts / updated content

### ISSUE THREAD

**Issue by streamgao** [eh3rrera/node-amp-live-list#1]
does amp live list support it?

https://github.com/streamgao/node-amp-live-list
I'm trying to hit with different endpoints

**Comment by streamgao** [comment]
solved ... https://github.com/streamgao/node-amp-live-list/commit/23ffa75a599ab5ec944914c815188223c73c8fe5

**Comment by eh3rrera** [comment]
Sorry for the late reply,

Glad you find the answer! 👍 

I didn't implement update/delete, but yes, it can be done with the corresponding attributes `data-update-time` and `data-tombstone`.

Thanks for the link to your solution!
