### ISSUE TITLE
res.render called multiple times

### ISSUE THREAD

**Issue by khanbaba** [eh3rrera/node-amp-live-list#2]
Hi the res.renders called multiple times.
What is the problem?
This is a performance bug.
How should i change to fix this?

**Comment by eh3rrera** [comment]
Hi.

I'm sorry, I don't know why this is happening.

The `amp-live-list` component is supposed to poll the server constantly (the time is configured with the `data-poll-interval` attribute), but you're not referring to this behavior, are you?

Have you tried with different browsers? Maybe an extension of your browser is doing this? https://stackoverflow.com/questions/13150277/express-request-is-called-twice

**Comment by khanbaba** [comment]
Yes. AMP Validator extension on chromium was the source of problem.
Thanks @eh3rrera

**Comment by eh3rrera** [comment]
You're welcome @khanbaba :)
